#![allow(missing_docs)]

//! Event payloads and handler prop types used by the retained UI runtime.

use crate::Cursor;
use crate::platform::input::{Key, PointerType, WheelDeltaMode, WheelPhase};

/// Re-export so `crate::ui` users don't need a separate platform import.
pub use crate::platform::input::Modifiers;
use crate::ui::node_id::{EventTarget, NodeId, Rect};
use std::ptr::NonNull;
use crate::view::base_component::TextAreaRenderString;
use smol_str::SmolStr;
use std::cell::RefCell;
use std::fmt;
use std::rc::Rc;
use std::sync::atomic::{AtomicU64, Ordering};

/// Canonical pointer button type. Aliased from
/// [`crate::platform::input::PlatformPointerButton`]; ui and viewport
/// layers both use the same type since Sprint 7.
pub use crate::platform::input::PlatformPointerButton as PointerButton;

// `KeyModifiers` alias removed in Sprint 7. Use [`Modifiers`] from
// `crate::platform::input` (re-exported via `crate::ui::Modifiers`).

#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct PointerButtons {
    pub left: bool,
    pub right: bool,
    pub middle: bool,
    pub back: bool,
    pub forward: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ViewportListenerHandle(pub u64);

#[derive(Clone)]
pub struct PointerUpUntilHandler {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerUpEvent) -> bool>>,
}

impl PointerUpUntilHandler {
    pub fn new<F>(handler: F) -> Self
    where
        F: FnMut(&mut PointerUpEvent) -> bool + 'static,
    {
        Self {
            id: next_handler_id(),
            handler: Rc::new(RefCell::new(handler)),
        }
    }

    pub fn id(&self) -> u64 {
        self.id
    }

    pub fn call(&self, event: &mut PointerUpEvent) -> bool {
        (self.handler.borrow_mut())(event)
    }
}

impl PartialEq for PointerUpUntilHandler {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl fmt::Debug for PointerUpUntilHandler {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PointerUpUntilHandler")
            .field("id", &self.id)
            .finish()
    }
}

/// Dispatch lifecycle phase.
///
/// Mirrors the W3C DOM `Event.eventPhase` values. rfgui currently runs no
/// capturing phase (no capture-listener API yet); dispatchers set
/// [`EventPhase::AtTarget`] when invoking the hit node and
/// [`EventPhase::Bubbling`] while walking ancestors. [`EventPhase::None`] is
/// the default for freshly built metas and for synthetic events that never
/// bubble (e.g. direct focus/blur).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EventPhase {
    /// Event not currently being dispatched along a path, or dispatch
    /// completed. Synthetic single-target events also stay in this phase.
    #[default]
    None,
    /// Root-to-target walk. Not yet emitted by rfgui.
    Capturing,
    /// Listeners on the original target run.
    AtTarget,
    /// Target-to-root walk; ancestor listeners run here.
    Bubbling,
}

/// Where an event originated. Distinguishes real platform input from
/// engine-synthesised or user-scripted events so handlers and a11y tooling
/// can react differently (e.g. screen readers only trust `Platform`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EventSource {
    /// Produced by the platform backend (winit, DOM, headless host).
    #[default]
    Platform,
    /// Generated by the engine itself (focus queue, hover enter/leave
    /// transitions, pointer-capture releases, …).
    Synthetic,
    /// Dispatched programmatically by user code.
    Scripted,
    /// Injected by an accessibility tool (screen reader, IME test harness).
    Accessibility,
}

/// Scroll alignment requested by [`EventCommand::ScrollIntoView`].
/// Matches the DOM `ScrollLogicalPosition` options used by
/// `Element.scrollIntoView`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ScrollAlignment {
    /// Scroll as little as possible to make the target visible.
    #[default]
    Nearest,
    /// Align the target to the start (top for block, left for inline) of
    /// the scroll container.
    Start,
    /// Align the target to the center of the scroll container.
    Center,
    /// Align the target to the end (bottom / right).
    End,
}

/// Options for [`EventCommand::ScrollIntoView`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ScrollIntoViewOptions {
    /// Block-axis (vertical) alignment.
    pub block: ScrollAlignment,
    /// Inline-axis (horizontal) alignment.
    pub inline: ScrollAlignment,
    /// Animate the scroll rather than jumping. Engine honours this when
    /// a scroll transition plugin is available; otherwise the action
    /// completes instantly.
    pub smooth: bool,
}

/// Commands a handler can push onto the dispatch queue to request a
/// viewport- or host-level side effect. Applied by the viewport after the
/// event finishes bubbling.
#[derive(Clone, Debug)]
pub enum EventCommand {
    AddPointerMoveListener(PointerMoveHandlerProp),
    AddPointerUpListener(PointerUpHandlerProp),
    AddPointerUpListenerUntil(PointerUpUntilHandler),
    SetFocus(Option<NodeId>),
    SetCursor(Option<Cursor>),
    SelectTextRangeAll(NodeId),
    SelectTextRange {
        target_id: NodeId,
        start: usize,
        end: usize,
    },
    RemoveListener(ViewportListenerHandle),
    // --- Sprint 5 command additions ---
    /// Ask the runner to schedule another redraw.
    RequestRedraw,
    /// Write text to the host clipboard.
    WriteClipboard(String),
    /// Scroll the given node into view inside its nearest scrollable
    /// ancestor.
    ScrollIntoView {
        target_id: NodeId,
        options: ScrollIntoViewOptions,
    },
    /// Acquire (`Some(node_id)`) or release (`None`) the keyboard capture.
    /// While captured, all key events route to that node regardless of
    /// focus (used for modal overlays, tooltips absorbing Esc, …).
    KeyboardCapture(Option<NodeId>),
    /// Host window lifecycle op.
    Window(crate::platform::WindowCommand),
    /// IME control op.
    Ime(crate::platform::ImeCommand),
    // --- Sprint 6 command additions ---
    /// Start a drag operation originating from the current target.
    /// Runner picks up the request via `PlatformRequests.pending_drag`
    /// and hands it to the OS drag machinery.
    StartDrag {
        source_id: NodeId,
        payload: Vec<DragPayload>,
        effect_allowed: DragEffect,
    },
    /// Ask the runner to read the system clipboard and dispatch the
    /// result as a [`PasteEvent`] to the focused node.
    RequestPaste,
}

struct EventMetaState {
    /// Monotonic id assigned at construction. Useful for logs, replays, and
    /// correlating an event across layers.
    event_id: u64,
    // Target / current_target / related_target are kept flat (id + bounds)
    // instead of as owned `EventTarget`s so the stored state has no
    // lifetime. The viewport reference lives in `viewport_ptr` below; each
    // getter re-assembles a lifetime-bound `EventTarget<'_>` on demand.
    target_id: NodeId,
    target_bounds: Rect,
    target_local_bounds: Rect,
    current_target_id: NodeId,
    current_target_bounds: Rect,
    current_target_local_bounds: Rect,
    /// For pair-style events: the "other" node.
    ///
    /// - `PointerEnter` / `PointerLeave`: previously / next-hovered node
    /// - `Focus`: blur-source node (where focus moved from)
    /// - `Blur`: focus-destination node (where focus moved to)
    ///
    /// `None` when no counterpart exists (e.g. first focus, pointer
    /// entering from outside the window).
    related_target_id: Option<NodeId>,
    related_target_bounds: Rect,
    related_target_local_bounds: Rect,
    /// Raw pointer to the dispatching viewport. Set by the dispatch layer
    /// on entry and cleared on exit as a second line of defence against
    /// `meta.clone()` leaks. Used for per-node state accessors
    /// (hovered / focused).
    ///
    /// SAFETY: dereferenced only in `EventTarget` getters, which rebind
    /// the reference to the borrow lifetime of `&self` on `EventMeta`.
    /// The target cannot outlive that borrow, so the pointer's pointee
    /// stays valid for the full lifetime of the returned reference.
    viewport_ptr: Option<NonNull<crate::view::viewport::Viewport>>,
    /// Ancestor chain from `target` up to the containing root (inclusive of
    /// both ends). Populated by the viewport dispatch layer when it has the
    /// tree available; empty for synthetic events where no path was computed.
    path: Rc<Vec<NodeId>>,
    phase: EventPhase,
    source: EventSource,
    bubbles: bool,
    cancelable: bool,
    propagation_stopped: bool,
    /// Set by `stop_immediate_propagation`. Stronger than
    /// `propagation_stopped`: halts remaining listeners at the *current*
    /// target too, not just ancestors.
    immediate_propagation_stopped: bool,
    default_prevented: bool,
    /// Former `keep_focus_requested`. True when a handler asked the
    /// dispatcher to preserve the existing focus in spite of the default
    /// focus-change behaviour (e.g. pointer down inside a popup that
    /// should not steal focus from the owning input).
    focus_change_suppressed: bool,
    /// Set by a handler to signal the platform layer that the event was
    /// consumed (used to swallow system shortcuts, IME passthrough, …).
    /// Independent from `propagation_stopped`: a handler can let the event
    /// keep bubbling for local observers while still claiming the platform
    /// side.
    handled: bool,
    pointer_capture_target_id: Option<NodeId>,
    viewport_listener_actions: Vec<EventCommand>,
}

impl Default for EventMetaState {
    fn default() -> Self {
        Self {
            event_id: next_event_id(),
            target_id: NodeId::default(),
            target_bounds: Rect::default(),
            target_local_bounds: Rect::default(),
            current_target_id: NodeId::default(),
            current_target_bounds: Rect::default(),
            current_target_local_bounds: Rect::default(),
            related_target_id: None,
            related_target_bounds: Rect::default(),
            related_target_local_bounds: Rect::default(),
            viewport_ptr: None,
            path: Rc::new(Vec::new()),
            phase: EventPhase::default(),
            source: EventSource::default(),
            bubbles: true,
            cancelable: true,
            propagation_stopped: false,
            immediate_propagation_stopped: false,
            default_prevented: false,
            focus_change_suppressed: false,
            handled: false,
            pointer_capture_target_id: None,
            viewport_listener_actions: Vec::new(),
        }
    }
}

fn next_event_id() -> u64 {
    static NEXT_ID: AtomicU64 = AtomicU64::new(1);
    NEXT_ID.fetch_add(1, Ordering::Relaxed)
}

#[derive(Clone)]
pub struct EventMeta {
    state: Rc<RefCell<EventMetaState>>,
}

impl fmt::Debug for EventMeta {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let state = self.state.borrow();
        f.debug_struct("EventMeta")
            .field("event_id", &state.event_id)
            .field("target_id", &state.target_id)
            .field("current_target_id", &state.current_target_id)
            .field("phase", &state.phase)
            .field("source", &state.source)
            .field("propagation_stopped", &state.propagation_stopped)
            .field("default_prevented", &state.default_prevented)
            .field("handled", &state.handled)
            .finish()
    }
}

impl EventMeta {
    pub fn new(target_id: NodeId) -> Self {
        Self {
            state: Rc::new(RefCell::new(EventMetaState {
                target_id,
                current_target_id: target_id,
                ..EventMetaState::default()
            })),
        }
    }

    /// Construct an `EventMeta` seeded with a full [`EventTarget`]
    /// (id + bounds). Prefer this over [`Self::new`] at dispatch sites
    /// that already know the node's geometry.
    pub fn with_target(target: EventTarget<'_>) -> Self {
        Self {
            state: Rc::new(RefCell::new(EventMetaState {
                target_id: target.id,
                target_bounds: target.bounds,
                target_local_bounds: target.local_bounds,
                current_target_id: target.id,
                current_target_bounds: target.bounds,
                current_target_local_bounds: target.local_bounds,
                ..EventMetaState::default()
            })),
        }
    }

    /// Node the event is dispatched to (the hit-test result or focused
    /// node). Stable for the duration of the dispatch. The returned
    /// `EventTarget<'_>`'s lifetime is bound to `&self`, so callers cannot
    /// leak it beyond the current handler call.
    pub fn target(&self) -> EventTarget<'_> {
        let (id, bounds, local_bounds) = {
            let s = self.state.borrow();
            (s.target_id, s.target_bounds, s.target_local_bounds)
        };
        self.rebind(EventTarget::snapshot(id, bounds, local_bounds))
    }

    /// Node currently processing the event as it bubbles. Changes as the
    /// dispatch walks up ancestors.
    pub fn current_target(&self) -> EventTarget<'_> {
        let (id, bounds, local_bounds) = {
            let s = self.state.borrow();
            (
                s.current_target_id,
                s.current_target_bounds,
                s.current_target_local_bounds,
            )
        };
        self.rebind(EventTarget::snapshot(id, bounds, local_bounds))
    }

    pub fn target_id(&self) -> NodeId {
        self.state.borrow().target_id
    }

    pub fn current_target_id(&self) -> NodeId {
        self.state.borrow().current_target_id
    }

    pub(crate) fn set_target_id(&mut self, target_id: NodeId) {
        let mut state = self.state.borrow_mut();
        state.target_id = target_id;
        state.target_bounds = Rect::default();
        state.target_local_bounds = Rect::default();
        state.current_target_id = target_id;
        state.current_target_bounds = Rect::default();
        state.current_target_local_bounds = Rect::default();
    }

    pub(crate) fn set_current_target_id(&mut self, current_target_id: NodeId) {
        self.state.borrow_mut().current_target_id = current_target_id;
    }

    /// Replace the `target` (the node that was originally hit). Usually
    /// called once at dispatch start.
    #[allow(dead_code)]
    pub(crate) fn set_target(&mut self, target: EventTarget<'_>) {
        let mut state = self.state.borrow_mut();
        state.target_id = target.id;
        state.target_bounds = target.bounds;
        state.target_local_bounds = target.local_bounds;
        state.current_target_id = target.id;
        state.current_target_bounds = target.bounds;
        state.current_target_local_bounds = target.local_bounds;
    }

    /// Update the `current_target` as the event bubbles up. Prefer this
    /// over [`Self::set_current_target_id`] so ancestor bounds propagate
    /// into handlers.
    pub(crate) fn set_current_target(&mut self, current_target: EventTarget<'_>) {
        let mut state = self.state.borrow_mut();
        state.current_target_id = current_target.id;
        state.current_target_bounds = current_target.bounds;
        state.current_target_local_bounds = current_target.local_bounds;
    }

    /// Internal: rebind an `EventTarget` to this meta's stored viewport
    /// pointer, producing one whose lifetime is the borrow of `&self`.
    ///
    /// SAFETY: `viewport_ptr` is set by the dispatch layer on entry to a
    /// dispatch call and cleared on exit. While set, the pointee is live
    /// for the full duration of `&self`'s borrow. Returned reference
    /// therefore cannot outlive the pointee.
    fn rebind<'a>(&'a self, mut target: EventTarget<'a>) -> EventTarget<'a> {
        if let Some(ptr) = self.state.borrow().viewport_ptr {
            // SAFETY: see method doc. Raw ptr is only consumed here.
            target.viewport = Some(unsafe { ptr.as_ref() });
        }
        target
    }

    /// Install the dispatching viewport on this meta so lazy
    /// `EventTarget` accessors can walk the tree / read per-node state.
    /// Arena access goes through `viewport.node_arena()` — single source
    /// of truth under Approach C.
    #[allow(dead_code)]
    pub(crate) fn attach_dispatch_ctx(
        &mut self,
        viewport: &crate::view::viewport::Viewport,
    ) {
        self.state.borrow_mut().viewport_ptr = Some(NonNull::from(viewport));
    }

    /// Second line of defence: the dispatch layer calls this on exit so
    /// even if a handler clones the meta out of scope, `EventTarget`
    /// accessors return safe defaults afterwards instead of dereferencing
    /// a possibly-invalidated pointer.
    #[allow(dead_code)]
    pub(crate) fn detach_dispatch_ctx(&mut self) {
        self.state.borrow_mut().viewport_ptr = None;
    }

    /// Monotonic identifier assigned at construction. Stable for the
    /// lifetime of the event; use for log correlation and trace spans.
    pub fn event_id(&self) -> u64 {
        self.state.borrow().event_id
    }

    /// Current dispatch lifecycle phase. See [`EventPhase`].
    pub fn phase(&self) -> EventPhase {
        self.state.borrow().phase
    }

    pub(crate) fn set_phase(&mut self, phase: EventPhase) {
        self.state.borrow_mut().phase = phase;
    }

    /// Origin of the event (platform input, engine-synthetic, user-scripted,
    /// or accessibility tool).
    pub fn source(&self) -> EventSource {
        self.state.borrow().source
    }

    #[allow(dead_code)]
    pub(crate) fn set_source(&mut self, source: EventSource) {
        self.state.borrow_mut().source = source;
    }

    /// True when the event came from real platform input (shorthand for
    /// `source() == EventSource::Platform`). Mirrors DOM `isTrusted`.
    pub fn is_trusted(&self) -> bool {
        self.state.borrow().source == EventSource::Platform
    }

    /// Whether the event bubbles up the ancestor chain. Most pointer/key
    /// events bubble; `PointerEnter` / `PointerLeave` do not.
    pub fn bubbles(&self) -> bool {
        self.state.borrow().bubbles
    }

    #[allow(dead_code)]
    pub(crate) fn set_bubbles(&mut self, bubbles: bool) {
        self.state.borrow_mut().bubbles = bubbles;
    }

    /// Whether [`prevent_default`] has any effect for this event.
    pub fn cancelable(&self) -> bool {
        self.state.borrow().cancelable
    }

    #[allow(dead_code)]
    pub(crate) fn set_cancelable(&mut self, cancelable: bool) {
        self.state.borrow_mut().cancelable = cancelable;
    }

    /// Tell the dispatcher to skip the platform's default action for this
    /// event (e.g. suppress a textarea inserting a character, block the
    /// browser from scrolling on Space). No-op if the event is not
    /// [`cancelable`](Self::cancelable).
    pub fn prevent_default(&mut self) {
        let mut state = self.state.borrow_mut();
        if state.cancelable {
            state.default_prevented = true;
        }
    }

    pub fn default_prevented(&self) -> bool {
        self.state.borrow().default_prevented
    }

    pub fn propagation_stopped(&self) -> bool {
        self.state.borrow().propagation_stopped
    }

    pub fn stop_propagation(&mut self) {
        self.state.borrow_mut().propagation_stopped = true;
    }

    /// Stronger form of [`stop_propagation`]: also prevents any remaining
    /// listeners on the **current** target from running. Mirrors DOM
    /// `stopImmediatePropagation`.
    pub fn stop_immediate_propagation(&mut self) {
        let mut state = self.state.borrow_mut();
        state.propagation_stopped = true;
        state.immediate_propagation_stopped = true;
    }

    pub fn immediate_propagation_stopped(&self) -> bool {
        self.state.borrow().immediate_propagation_stopped
    }

    /// True when a handler has claimed responsibility for the event.
    /// Distinct from propagation: the event may still bubble for observers
    /// while the platform layer treats it as consumed (swallowing system
    /// shortcuts, IME passthrough, accessibility feedback).
    pub fn handled(&self) -> bool {
        self.state.borrow().handled
    }

    /// Mark the event as consumed by the handler. See [`handled`](Self::handled).
    pub fn mark_handled(&mut self) {
        self.state.borrow_mut().handled = true;
    }

    /// Ask the dispatcher to keep the existing focus, overriding the
    /// default focus-change behaviour (e.g. a pointer-down inside a popup
    /// that should not steal focus from the owning input).
    pub fn suppress_focus_change(&mut self) {
        self.state.borrow_mut().focus_change_suppressed = true;
    }

    pub fn focus_change_suppressed(&self) -> bool {
        self.state.borrow().focus_change_suppressed
    }

    pub fn request_pointer_capture(&mut self) {
        let current_target_id = self.state.borrow().current_target_id;
        self.state.borrow_mut().pointer_capture_target_id = Some(current_target_id);
    }

    pub fn pointer_capture_target_id(&self) -> Option<NodeId> {
        self.state.borrow().pointer_capture_target_id
    }

    /// Ancestor chain walked during dispatch: `target` first, root last
    /// (DOM `composedPath()` ordering). Empty when the dispatch site did
    /// not populate it (e.g. synthetic focus events, unit tests).
    ///
    /// Clones the shared path handle — cheap (`Rc` bump). Handlers that
    /// need to iterate many times should cache the returned `Rc`.
    pub fn composed_path(&self) -> Rc<Vec<NodeId>> {
        Rc::clone(&self.state.borrow().path)
    }

    /// Replace the dispatch path. Called by the viewport dispatcher before
    /// walking ancestors; user code should not need this.
    pub(crate) fn set_path(&mut self, path: Vec<NodeId>) {
        self.state.borrow_mut().path = Rc::new(path);
    }

    /// Counterpart node for pair-style events (see
    /// [`EventMetaState::related_target_id`] for semantics per event).
    pub fn related_target(&self) -> Option<EventTarget<'_>> {
        let (id, bounds, local_bounds) = {
            let s = self.state.borrow();
            (
                s.related_target_id?,
                s.related_target_bounds,
                s.related_target_local_bounds,
            )
        };
        Some(self.rebind(EventTarget::snapshot(id, bounds, local_bounds)))
    }

    /// Set the `related_target`. Called by the dispatcher when it knows the
    /// counterpart (previous hover, focus source, …).
    pub(crate) fn set_related_target(&mut self, related: Option<EventTarget<'_>>) {
        let mut state = self.state.borrow_mut();
        match related {
            Some(t) => {
                state.related_target_id = Some(t.id);
                state.related_target_bounds = t.bounds;
                state.related_target_local_bounds = t.local_bounds;
            }
            None => {
                state.related_target_id = None;
                state.related_target_bounds = Rect::default();
                state.related_target_local_bounds = Rect::default();
            }
        }
    }

    pub fn viewport(&self) -> EventViewport {
        EventViewport {
            state: self.state.clone(),
        }
    }

    pub(crate) fn take_viewport_listener_actions(&mut self) -> Vec<EventCommand> {
        std::mem::take(&mut self.state.borrow_mut().viewport_listener_actions)
    }

    pub(crate) fn text_selection_target(&self, target_id: NodeId) -> TextSelectionTarget {
        TextSelectionTarget {
            state: self.state.clone(),
            target_id,
        }
    }
}

#[derive(Clone)]
pub struct EventViewport {
    state: Rc<RefCell<EventMetaState>>,
}

impl fmt::Debug for EventViewport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let pending = self.state.borrow().viewport_listener_actions.len();
        f.debug_struct("EventViewport")
            .field("pending_actions", &pending)
            .finish()
    }
}

impl EventViewport {
    pub fn add_pointer_move_listener<F>(&mut self, handler: F) -> ViewportListenerHandle
    where
        F: FnMut(&mut PointerMoveEvent) + 'static,
    {
        let handler_prop = PointerMoveHandlerProp::new(handler);
        let handle = ViewportListenerHandle(handler_prop.id());
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::AddPointerMoveListener(handler_prop));
        handle
    }

    pub fn add_pointer_up_listener<F>(&mut self, handler: F) -> ViewportListenerHandle
    where
        F: FnMut(&mut PointerUpEvent) + 'static,
    {
        let handler_prop = PointerUpHandlerProp::new(handler);
        let handle = ViewportListenerHandle(handler_prop.id());
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::AddPointerUpListener(handler_prop));
        handle
    }

    pub fn add_pointer_up_listener_until<F>(&mut self, handler: F) -> ViewportListenerHandle
    where
        F: FnMut(&mut PointerUpEvent) -> bool + 'static,
    {
        let handler_prop = PointerUpUntilHandler::new(handler);
        let handle = ViewportListenerHandle(handler_prop.id());
        self.state.borrow_mut().viewport_listener_actions.push(
            EventCommand::AddPointerUpListenerUntil(handler_prop),
        );
        handle
    }

    pub fn remove_listener(&mut self, handle: ViewportListenerHandle) {
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::RemoveListener(handle));
    }

    pub fn set_cursor(&mut self, cursor: Option<Cursor>) {
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::SetCursor(cursor));
    }

    pub fn set_focus(&mut self, node_id: Option<NodeId>) {
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::SetFocus(node_id));
    }

    /// Request another redraw after this event finishes.
    pub fn request_redraw(&mut self) {
        self.push_action(EventCommand::RequestRedraw);
    }

    /// Queue a clipboard write. Runner delivers it to the OS clipboard
    /// after dispatch completes.
    pub fn write_clipboard(&mut self, text: impl Into<String>) {
        self.push_action(EventCommand::WriteClipboard(text.into()));
    }

    /// Scroll the given node into view inside its nearest scrollable
    /// ancestor, using `options` for alignment / smoothness.
    pub fn scroll_into_view(&mut self, target_id: NodeId, options: ScrollIntoViewOptions) {
        self.push_action(EventCommand::ScrollIntoView {
            target_id,
            options,
        });
    }

    /// Take keyboard capture for `node_id`. All subsequent key events
    /// route to this node regardless of focus, until
    /// [`Self::release_keyboard_capture`] or another `acquire` replaces it.
    pub fn acquire_keyboard_capture(&mut self, node_id: NodeId) {
        self.push_action(EventCommand::KeyboardCapture(Some(node_id)));
    }

    /// Release any active keyboard capture.
    pub fn release_keyboard_capture(&mut self) {
        self.push_action(EventCommand::KeyboardCapture(None));
    }

    /// Queue a host-window lifecycle command (close / minimize / title…).
    pub fn window_command(&mut self, command: crate::platform::WindowCommand) {
        self.push_action(EventCommand::Window(command));
    }

    /// Queue an IME control command (enable / disable / cursor rect).
    pub fn ime_command(&mut self, command: crate::platform::ImeCommand) {
        self.push_action(EventCommand::Ime(command));
    }

    /// Start a drag operation from `source_id` with the given payload.
    /// The runner relays the request to the OS drag machinery.
    pub fn start_drag(
        &mut self,
        source_id: NodeId,
        payload: Vec<DragPayload>,
        effect_allowed: DragEffect,
    ) {
        self.push_action(EventCommand::StartDrag {
            source_id,
            payload,
            effect_allowed,
        });
    }

    /// Request a paste from the OS clipboard. The runner drains this,
    /// reads the clipboard asynchronously if needed, and dispatches a
    /// [`PasteEvent`] back to the focused node.
    pub fn request_paste(&mut self) {
        self.push_action(EventCommand::RequestPaste);
    }

    fn push_action(&mut self, action: EventCommand) {
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(action);
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PointerEventData {
    pub viewport_x: f32,
    pub viewport_y: f32,
    pub local_x: f32,
    pub local_y: f32,
    pub button: Option<PointerButton>,
    pub buttons: PointerButtons,
    pub modifiers: Modifiers,
    pub pointer_id: u64,
    pub pointer_type: PointerType,
    pub pressure: f32,
    pub timestamp: crate::time::Instant,
}

/// Physical placement of a key on the keyboard. Orthogonal to the
/// [`Key`] enum — e.g. `Key::ShiftLeft` has `location = Left`, while
/// numpad digits have `location = Numpad`. Mirrors the W3C
/// `KeyboardEvent.location` values so web-origin code ports cleanly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum KeyLocation {
    /// Default location — most keys on the main block.
    #[default]
    Standard,
    /// Left-hand variant of a split key (Shift / Ctrl / Alt / Meta).
    Left,
    /// Right-hand variant of a split key.
    Right,
    /// Numeric keypad region (separate digits, operators, Enter).
    Numpad,
}

impl KeyLocation {
    /// Derive the conventional location for a [`Key`] variant. Handlers
    /// that want the W3C mapping without having to match on the full
    /// `Key` enum can use this.
    pub fn from_key(key: Key) -> Self {
        use Key::*;
        match key {
            ShiftLeft | ControlLeft | AltLeft | MetaLeft => Self::Left,
            ShiftRight | ControlRight | AltRight | MetaRight => Self::Right,
            NumberPad0 | NumberPad1 | NumberPad2 | NumberPad3 | NumberPad4 | NumberPad5
            | NumberPad6 | NumberPad7 | NumberPad8 | NumberPad9 | NumberPadAdd
            | NumberPadSubtract | NumberPadMultiply | NumberPadDivide | NumberPadDecimal
            | NumberPadEnter | NumberPadEqual => Self::Numpad,
            _ => Self::Standard,
        }
    }
}

#[derive(Debug, Clone)]
pub struct KeyEventData {
    /// Physical key identifier (layout-independent).
    pub key: Key,
    /// Layout-applied text output. `None` for non-character keys.
    pub characters: Option<SmolStr>,
    pub modifiers: Modifiers,
    pub repeat: bool,
    /// True while an IME composition is active. Handlers typically early-return
    /// so the IME can consume the key (e.g. Enter commits, not newline).
    pub is_composing: bool,
    /// Physical key region (Left / Right / Numpad / Standard). Derive
    /// from [`Key`] via [`KeyLocation::from_key`] if you didn't set it
    /// explicitly.
    pub location: KeyLocation,
    pub timestamp: crate::time::Instant,
}

impl KeyEventData {
    /// Convenience for shortcut matching: physical key equality plus exact
    /// (non-lock) modifier set, and not during IME composition.
    #[inline]
    pub fn shortcut(&self, key: Key, mods: Modifiers) -> bool {
        self.key == key && self.modifiers.exactly(mods) && !self.is_composing
    }
}

#[derive(Debug, Clone)]
pub struct PointerDownEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub viewport: EventViewport,
}

#[derive(Debug, Clone)]
pub struct PointerUpEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub viewport: EventViewport,
}

#[derive(Debug, Clone)]
pub struct PointerMoveEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub viewport: EventViewport,
}

/// Fires when a pointer first enters a node's bounds. Non-bubbling: only the
/// entered node sees it (matches DOM `mouseenter` / `pointerenter`). Pair
/// event; `meta.related_target()` holds the previously hovered node.
///
/// For a bubbling variant use [`PointerOverEvent`] (coming in a later phase).
#[derive(Debug, Clone)]
pub struct PointerEnterEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
}

/// Fires when a pointer leaves a node's bounds. Non-bubbling counterpart of
/// [`PointerEnterEvent`]; `meta.related_target()` holds the node the pointer
/// moved into (if any).
#[derive(Debug, Clone)]
pub struct PointerLeaveEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
}

#[derive(Debug, Clone)]
pub struct ClickEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    /// Consecutive-click counter. `1` for a single click, `2` for a
    /// double-click, `3` for a triple-click, etc. Resets to `1` when the
    /// gap since the previous click exceeds the platform threshold or the
    /// pointer moved beyond the click-slop radius (matches DOM
    /// `MouseEvent.detail`).
    pub click_count: u32,
}

/// Fired when the user spins the mouse wheel or performs a two-finger
/// trackpad scroll over a node. Bubbles. Handlers can call
/// `meta.prevent_default()` to suppress the viewport's default scroll
/// routing (useful for custom scroll containers or for trapping ctrl+wheel
/// as zoom).
#[derive(Debug, Clone)]
pub struct WheelEvent {
    pub meta: EventMeta,
    /// Pointer position (viewport-space logical pixels) at the time the
    /// wheel event was produced.
    pub viewport_x: f32,
    pub viewport_y: f32,
    /// Hit-tested node-local position (set by the dispatcher as it walks
    /// the ancestor chain).
    pub local_x: f32,
    pub local_y: f32,
    pub delta_x: f32,
    pub delta_y: f32,
    pub delta_mode: WheelDeltaMode,
    pub phase: WheelPhase,
    pub modifiers: Modifiers,
    pub timestamp: crate::time::Instant,
}

/// Fires when the user invokes the context-menu gesture — right pointer
/// click on desktop, long-press on touch, or the `ContextMenu` key on
/// keyboards that expose one. Bubbles. Cancel via `meta.prevent_default()`
/// to suppress the platform's native menu and show a custom one instead.
#[derive(Debug, Clone)]
pub struct ContextMenuEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
}

#[derive(Debug, Clone)]
pub struct KeyDownEvent {
    pub meta: EventMeta,
    pub key: KeyEventData,
}

#[derive(Debug, Clone)]
pub struct KeyUpEvent {
    pub meta: EventMeta,
    pub key: KeyEventData,
}

/// Origin classification for a [`TextInputEvent`]. Mirrors the subset of
/// DOM `InputEvent.inputType` values that rfgui actually distinguishes,
/// so apps can treat paste / IME commit differently from live typing
/// (e.g. coalesce into one undo step, trigger autocomplete only on
/// `Typing`, run a paste-size guard on `Paste`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum InputType {
    /// Keystroke-driven character input (the default path from
    /// platform text events). One char per event on most platforms, but
    /// some IMEs may batch.
    #[default]
    Typing,
    /// Text pasted from the system clipboard.
    Paste,
    /// Text delivered by a drag-and-drop payload.
    Drop,
    /// IME committed a composition (final, non-preedit text).
    ImeCommit,
    /// Programmatic insertion (e.g. set from code rather than user input).
    /// Useful for distinguishing model-driven updates from user actions
    /// inside a single `on_input` observer.
    Programmatic,
}

#[derive(Debug, Clone)]
pub struct TextInputEvent {
    pub meta: EventMeta,
    pub text: String,
    /// Origin of the inserted text. See [`InputType`] for semantics.
    pub input_type: InputType,
    /// Mirrors the originating key's `is_composing` flag (true while the
    /// IME composition window is open). `ImeCommit` events flip this
    /// false — the composition has closed by the time the commit fires.
    pub is_composing: bool,
}

#[derive(Debug, Clone)]
pub struct TextChangeEvent {
    pub meta: EventMeta,
    pub value: String,
}

/// Visual style hint attached to a span of preedit text. Mirrors the
/// subset of IME underline / highlight semantics used on Windows TSF,
/// macOS NSTextInputClient, and X11 XIM.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreeditStyle {
    /// Solid underline — typical default for the whole preedit.
    Underline,
    /// Dotted / dashed underline — often used for "not yet committed"
    /// regions in Japanese IME.
    DottedUnderline,
    /// Highlighted selection — the clause the user is currently editing
    /// (candidate highlight).
    Highlight,
}

/// One styled run inside the preedit text. Byte offsets are indices into
/// [`ImePreeditEvent::text`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PreeditAttribute {
    pub start: usize,
    pub end: usize,
    pub style: PreeditStyle,
}

#[derive(Debug, Clone)]
pub struct ImePreeditEvent {
    pub meta: EventMeta,
    pub text: String,
    /// Caret position inside `text`, as a `(start, end)` byte range. When
    /// `start == end` it's a caret; when different it's a selection.
    /// `None` means the IME did not report a caret (handler should place
    /// the caret at the end of `text`).
    pub cursor: Option<(usize, usize)>,
    /// Active selection / highlight inside the preedit text, independent
    /// of the caret. Some IMEs report cursor + selection separately; most
    /// report only one, in which case this is `None`.
    pub selection: Option<(usize, usize)>,
    /// Styled sub-runs for underline / highlight rendering. May be empty
    /// if the platform only delivers plain preedit text.
    pub attributes: Vec<PreeditAttribute>,
}

/// Fired when the IME commits a composition as final text. The text
/// travels through the regular text-input handler (via [`TextInputEvent`]
/// with `input_type = ImeCommit`) *and* as this dedicated event so apps
/// that want lifecycle observability can see the commit without
/// post-filtering `TextInputEvent`.
#[derive(Debug, Clone)]
pub struct ImeCommitEvent {
    pub meta: EventMeta,
    pub text: String,
}

/// Fired once when an IME composition starts. Useful for apps that want
/// to open a visual candidate window hint or suppress global shortcuts
/// during composition.
#[derive(Debug, Clone)]
pub struct ImeEnabledEvent {
    pub meta: EventMeta,
}

/// Fired once when an IME composition ends (either committed or
/// cancelled). Pairs with [`ImeEnabledEvent`].
#[derive(Debug, Clone)]
pub struct ImeDisabledEvent {
    pub meta: EventMeta,
}

/// Why focus changed. Lets handlers style the focus ring differently
/// for pointer clicks (no ring) vs keyboard navigation (visible ring),
/// matching the `:focus-visible` convention.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum FocusReason {
    /// Cause unknown or not classified — assume programmatic.
    #[default]
    Programmatic,
    /// User clicked / tapped the node.
    Pointer,
    /// User navigated via Tab, arrow keys, or another key.
    Keyboard,
    /// Keyboard shortcut or accelerator explicitly targeted the node.
    Shortcut,
    /// Focus restored automatically after the app regained host focus
    /// (e.g. window was re-activated).
    WindowActivation,
}

#[derive(Debug, Clone)]
pub struct FocusEvent {
    pub meta: EventMeta,
    pub reason: FocusReason,
}

#[derive(Clone)]
pub struct TextSelectionTarget {
    state: Rc<RefCell<EventMetaState>>,
    target_id: NodeId,
}

impl fmt::Debug for TextSelectionTarget {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TextSelectionTarget")
            .field("target_id", &self.target_id)
            .finish()
    }
}

impl TextSelectionTarget {
    pub fn select_all(&mut self) {
        self.state
            .borrow_mut()
            .viewport_listener_actions
            .push(EventCommand::SelectTextRangeAll(self.target_id));
    }

    pub fn select_range(&mut self, start: usize, end: usize) {
        self.state.borrow_mut().viewport_listener_actions.push(
            EventCommand::SelectTextRange {
                target_id: self.target_id,
                start,
                end,
            },
        );
    }
}

#[derive(Debug, Clone)]
pub struct TextAreaFocusEvent {
    pub meta: EventMeta,
    pub target: TextSelectionTarget,
}

#[derive(Debug, Clone)]
pub struct BlurEvent {
    pub meta: EventMeta,
    pub reason: FocusReason,
}

// ---------------------------------------------------------------------
// Drag & drop
// ---------------------------------------------------------------------

/// Payload carried by a drag operation. Mirrors the HTML
/// `DataTransfer.items` shape enough for text / file / custom mime
/// round-trips without being locked into the DOM model.
#[derive(Debug, Clone)]
pub enum DragPayload {
    /// Plain UTF-8 text. Maps to `text/plain` on platform clipboards.
    Text(String),
    /// File paths from the OS. Filled by the platform for inbound
    /// drops; outgoing file drags can set this too if the platform
    /// supports file-drag export.
    Files(Vec<std::path::PathBuf>),
    /// Arbitrary mime-tagged binary blob (e.g. `image/png`,
    /// `application/json`).
    Custom {
        mime: SmolStr,
        bytes: Vec<u8>,
    },
}

/// Operations the source allows for a drag — mirrors HTML5
/// `DataTransfer.effectAllowed`. Target handlers set `drop_effect` on
/// [`DragOverEvent`] to pick which one actually applies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DragEffect {
    #[default]
    None,
    Copy,
    Move,
    Link,
    /// Any of Copy / Move / Link.
    All,
}

/// Mutable payload container for [`DragStartEvent`] (source fills it)
/// and readable view for [`DragOverEvent`] / [`DropEvent`] (target
/// consumes it). Uses interior mutability so multiple handlers along
/// the bubble path can add items.
#[derive(Clone)]
pub struct DataTransfer {
    state: Rc<RefCell<DataTransferState>>,
}

#[derive(Default)]
struct DataTransferState {
    items: Vec<DragPayload>,
    effect_allowed: DragEffect,
}

impl fmt::Debug for DataTransfer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let state = self.state.borrow();
        f.debug_struct("DataTransfer")
            .field("item_count", &state.items.len())
            .field("effect_allowed", &state.effect_allowed)
            .finish()
    }
}

impl DataTransfer {
    pub fn new() -> Self {
        Self {
            state: Rc::new(RefCell::new(DataTransferState::default())),
        }
    }

    pub fn with_items(items: Vec<DragPayload>) -> Self {
        Self {
            state: Rc::new(RefCell::new(DataTransferState {
                items,
                effect_allowed: DragEffect::default(),
            })),
        }
    }

    /// Append a payload item. Called by `dragstart` handlers to seed
    /// what the source is offering.
    pub fn add(&mut self, item: DragPayload) {
        self.state.borrow_mut().items.push(item);
    }

    /// Convenience: push a text item.
    pub fn set_text(&mut self, text: impl Into<String>) {
        self.add(DragPayload::Text(text.into()));
    }

    /// Snapshot current items.
    pub fn items(&self) -> Vec<DragPayload> {
        self.state.borrow().items.clone()
    }

    /// First text item, if any.
    pub fn text(&self) -> Option<String> {
        self.state.borrow().items.iter().find_map(|it| match it {
            DragPayload::Text(s) => Some(s.clone()),
            _ => None,
        })
    }

    /// First file list, if any.
    pub fn files(&self) -> Option<Vec<std::path::PathBuf>> {
        self.state.borrow().items.iter().find_map(|it| match it {
            DragPayload::Files(paths) => Some(paths.clone()),
            _ => None,
        })
    }

    pub fn effect_allowed(&self) -> DragEffect {
        self.state.borrow().effect_allowed
    }

    pub fn set_effect_allowed(&mut self, effect: DragEffect) {
        self.state.borrow_mut().effect_allowed = effect;
    }
}

impl Default for DataTransfer {
    fn default() -> Self {
        Self::new()
    }
}

/// Fired when a drag gesture starts on the source node. Handlers fill
/// `data` with what's being dragged and optionally set
/// `effect_allowed`. Calling `meta.prevent_default()` cancels the drag
/// before it leaves the source.
#[derive(Debug, Clone)]
pub struct DragStartEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub data: DataTransfer,
}

/// Fired on each node the drag pointer enters while the drag is
/// active. Handlers that accept the drop call `accept(effect)` to tell
/// the engine to keep the cursor targeted here; otherwise the default
/// is to refuse (and move on to the ancestor).
#[derive(Debug, Clone)]
pub struct DragOverEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub data: DataTransfer,
    /// Set to the chosen [`DragEffect`] when the handler wants to
    /// accept the drop. Defaults to `None` (refused).
    pub drop_effect: Option<DragEffect>,
}

impl DragOverEvent {
    /// Accept the drop with the given effect, preventing the engine
    /// from falling through to the ancestor and setting the cursor
    /// hint.
    pub fn accept(&mut self, effect: DragEffect) {
        self.drop_effect = Some(effect);
        self.meta.prevent_default();
    }
}

/// Fired when the drag pointer leaves a node that previously saw
/// `dragover`. Non-bubbling.
#[derive(Debug, Clone)]
pub struct DragLeaveEvent {
    pub meta: EventMeta,
}

/// Fired when the drag is released over a node that accepted it in
/// `dragover`. `data` holds what was dragged; handlers should read
/// from it before returning.
#[derive(Debug, Clone)]
pub struct DropEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub data: DataTransfer,
    pub effect: DragEffect,
}

/// Fired on the source node after the drag ends, regardless of
/// whether a drop succeeded. `effect` holds what the target actually
/// applied (or `None` for a cancelled drag).
#[derive(Debug, Clone)]
pub struct DragEndEvent {
    pub meta: EventMeta,
    pub pointer: PointerEventData,
    pub effect: Option<DragEffect>,
}

// ---------------------------------------------------------------------
// Clipboard (element-level)
// ---------------------------------------------------------------------

/// Fired on the focused node when the user triggers Copy (Ctrl/Cmd+C
/// or context-menu Copy). Handlers fill `data` with the text/payload
/// to place on the clipboard. Calling `meta.prevent_default()` stops
/// the engine's default copy (selected text).
#[derive(Debug, Clone)]
pub struct CopyEvent {
    pub meta: EventMeta,
    pub data: DataTransfer,
}

/// Like [`CopyEvent`] but handlers are expected to also delete the
/// selected region after filling `data`.
#[derive(Debug, Clone)]
pub struct CutEvent {
    pub meta: EventMeta,
    pub data: DataTransfer,
}

/// Fired on the focused node when the user triggers Paste. `data`
/// carries what the OS clipboard held at the time. Call
/// `meta.prevent_default()` to stop the engine's default insertion.
#[derive(Debug, Clone)]
pub struct PasteEvent {
    pub meta: EventMeta,
    pub data: DataTransfer,
}

#[derive(Clone)]
pub struct PointerDownHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerDownEvent)>>,
}

#[derive(Clone)]
pub struct PointerUpHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerUpEvent)>>,
}

#[derive(Clone)]
pub struct PointerMoveHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerMoveEvent)>>,
}

#[derive(Clone)]
pub struct PointerEnterHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerEnterEvent)>>,
}

#[derive(Clone)]
pub struct PointerLeaveHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PointerLeaveEvent)>>,
}

#[derive(Clone)]
pub struct ClickHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut ClickEvent)>>,
}

#[derive(Clone)]
pub struct ContextMenuHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut ContextMenuEvent)>>,
}

#[derive(Clone)]
pub struct WheelHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut WheelEvent)>>,
}

#[derive(Clone)]
pub struct KeyDownHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut KeyDownEvent)>>,
}

#[derive(Clone)]
pub struct KeyUpHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut KeyUpEvent)>>,
}

#[derive(Clone)]
pub struct FocusHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut FocusEvent)>>,
}

#[derive(Clone)]
pub struct BlurHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut BlurEvent)>>,
}

#[derive(Clone)]
pub struct ImeCommitHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut ImeCommitEvent)>>,
}

#[derive(Clone)]
pub struct ImeEnabledHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut ImeEnabledEvent)>>,
}

#[derive(Clone)]
pub struct ImeDisabledHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut ImeDisabledEvent)>>,
}

#[derive(Clone)]
pub struct DragStartHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut DragStartEvent)>>,
}

#[derive(Clone)]
pub struct DragOverHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut DragOverEvent)>>,
}

#[derive(Clone)]
pub struct DragLeaveHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut DragLeaveEvent)>>,
}

#[derive(Clone)]
pub struct DropHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut DropEvent)>>,
}

#[derive(Clone)]
pub struct DragEndHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut DragEndEvent)>>,
}

#[derive(Clone)]
pub struct CopyHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut CopyEvent)>>,
}

#[derive(Clone)]
pub struct CutHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut CutEvent)>>,
}

#[derive(Clone)]
pub struct PasteHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut PasteEvent)>>,
}

#[derive(Clone)]
pub struct TextAreaFocusHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut TextAreaFocusEvent)>>,
}

#[derive(Clone)]
pub struct TextChangeHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut TextChangeEvent)>>,
}

#[derive(Clone)]
pub struct TextAreaRenderHandlerProp {
    id: u64,
    handler: Rc<RefCell<dyn FnMut(&mut TextAreaRenderString)>>,
}

pub struct NoArgHandler<F>(F);

pub fn no_arg_handler<F>(handler: F) -> NoArgHandler<F> {
    NoArgHandler(handler)
}

pub trait IntoEventHandlerProp<T> {
    fn into_event_handler_prop(self) -> T;
}

/// Maps a handler-prop field type to the event it receives.
///
/// Implemented automatically by `impl_handler_prop!` for every
/// `Option<HandlerProp>`. Used by `rsx!` to anchor closure argument inference
/// without the macro knowing any event names: the macro passes the field
/// reference to `__rsx_ev_to_handler`, which constrains the closure arg type
/// via `F: FnMut(&mut O::Event)` and converts straight into `H` via `From<F>`
/// — one generic call instead of two.
#[doc(hidden)]
pub trait __RsxHandlerField {
    type Event;
}

#[doc(hidden)]
#[inline]
pub fn __rsx_ev_to_handler<O, F, H>(_field: &O, f: F) -> H
where
    O: __RsxHandlerField,
    F: FnMut(&mut O::Event) + 'static,
    H: From<F>,
{
    H::from(f)
}

#[doc(hidden)]
#[inline]
pub fn __rsx_ev_no_arg_to_handler<O, F, H>(_field: &O, f: F) -> H
where
    O: __RsxHandlerField,
    F: FnMut() + 'static,
    H: From<NoArgHandler<F>>,
{
    H::from(NoArgHandler(f))
}

#[doc(hidden)]
pub fn __rsx_ev_closure<O, F>(_field: &O, f: F) -> F
where
    O: __RsxHandlerField,
    F: FnMut(&mut O::Event) + 'static,
{
    f
}

#[doc(hidden)]
pub fn __rsx_ev_no_arg<O, F>(_field: &O, f: F) -> NoArgHandler<F>
where
    O: __RsxHandlerField,
    F: FnMut() + 'static,
{
    NoArgHandler(f)
}

fn next_handler_id() -> u64 {
    static NEXT_ID: AtomicU64 = AtomicU64::new(1);
    NEXT_ID.fetch_add(1, Ordering::Relaxed)
}

macro_rules! impl_handler_prop {
    ($ty:ident, $event_ty:ty) => {
        impl $ty {
            pub fn new<F>(handler: F) -> Self
            where
                F: for<'a> FnMut(&'a mut $event_ty) + 'static,
            {
                Self {
                    id: next_handler_id(),
                    handler: Rc::new(RefCell::new(handler)),
                }
            }

            pub fn id(&self) -> u64 {
                self.id
            }

            pub fn call(&self, event: &mut $event_ty) {
                (self.handler.borrow_mut())(event);
            }
        }

        impl PartialEq for $ty {
            fn eq(&self, other: &Self) -> bool {
                self.id == other.id
            }
        }

        impl fmt::Debug for $ty {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_struct(stringify!($ty))
                    .field("id", &self.id)
                    .finish()
            }
        }

        impl<F> From<F> for $ty
        where
            F: for<'a> FnMut(&'a mut $event_ty) + 'static,
        {
            fn from(handler: F) -> Self {
                $ty::new(handler)
            }
        }

        impl<F> From<NoArgHandler<F>> for $ty
        where
            F: FnMut() + 'static,
        {
            fn from(handler: NoArgHandler<F>) -> Self {
                let mut f = handler.0;
                $ty::new(move |_event: &mut $event_ty| f())
            }
        }

        impl __RsxHandlerField for ::core::option::Option<$ty> {
            type Event = $event_ty;
        }
    };
}

macro_rules! impl_into_event_handler_prop {
    ($handler_ty:ty, $event_ty:ty, $into_fn:ident) => {
        impl IntoEventHandlerProp<$handler_ty> for $handler_ty {
            fn into_event_handler_prop(self) -> $handler_ty {
                self
            }
        }

        impl<F> IntoEventHandlerProp<$handler_ty> for F
        where
            F: for<'a> FnMut(&'a mut $event_ty) + 'static,
        {
            fn into_event_handler_prop(self) -> $handler_ty {
                <$handler_ty>::new(self)
            }
        }

        impl<F> IntoEventHandlerProp<$handler_ty> for NoArgHandler<F>
        where
            F: FnMut() + 'static,
        {
            fn into_event_handler_prop(self) -> $handler_ty {
                let mut handler = self.0;
                <$handler_ty>::new(move |_event: &mut $event_ty| {
                    handler();
                })
            }
        }

        pub fn $into_fn<H>(handler: H) -> $handler_ty
        where
            H: IntoEventHandlerProp<$handler_ty>,
        {
            handler.into_event_handler_prop()
        }
    };
}

impl_handler_prop!(PointerDownHandlerProp, PointerDownEvent);
impl_handler_prop!(PointerUpHandlerProp, PointerUpEvent);
impl_handler_prop!(PointerMoveHandlerProp, PointerMoveEvent);
impl_handler_prop!(PointerEnterHandlerProp, PointerEnterEvent);
impl_handler_prop!(PointerLeaveHandlerProp, PointerLeaveEvent);
impl_handler_prop!(ClickHandlerProp, ClickEvent);
impl_handler_prop!(ContextMenuHandlerProp, ContextMenuEvent);
impl_handler_prop!(WheelHandlerProp, WheelEvent);
impl_handler_prop!(KeyDownHandlerProp, KeyDownEvent);
impl_handler_prop!(KeyUpHandlerProp, KeyUpEvent);
impl_handler_prop!(FocusHandlerProp, FocusEvent);
impl_handler_prop!(BlurHandlerProp, BlurEvent);
impl_handler_prop!(ImeCommitHandlerProp, ImeCommitEvent);
impl_handler_prop!(ImeEnabledHandlerProp, ImeEnabledEvent);
impl_handler_prop!(ImeDisabledHandlerProp, ImeDisabledEvent);
impl_handler_prop!(DragStartHandlerProp, DragStartEvent);
impl_handler_prop!(DragOverHandlerProp, DragOverEvent);
impl_handler_prop!(DragLeaveHandlerProp, DragLeaveEvent);
impl_handler_prop!(DropHandlerProp, DropEvent);
impl_handler_prop!(DragEndHandlerProp, DragEndEvent);
impl_handler_prop!(CopyHandlerProp, CopyEvent);
impl_handler_prop!(CutHandlerProp, CutEvent);
impl_handler_prop!(PasteHandlerProp, PasteEvent);
impl_handler_prop!(TextAreaFocusHandlerProp, TextAreaFocusEvent);
impl_handler_prop!(TextChangeHandlerProp, TextChangeEvent);
impl_handler_prop!(TextAreaRenderHandlerProp, TextAreaRenderString);

impl_into_event_handler_prop!(
    PointerDownHandlerProp,
    PointerDownEvent,
    into_pointer_down_handler
);
impl_into_event_handler_prop!(PointerUpHandlerProp, PointerUpEvent, into_pointer_up_handler);
impl_into_event_handler_prop!(
    PointerMoveHandlerProp,
    PointerMoveEvent,
    into_pointer_move_handler
);
impl_into_event_handler_prop!(
    PointerEnterHandlerProp,
    PointerEnterEvent,
    into_pointer_enter_handler
);
impl_into_event_handler_prop!(
    PointerLeaveHandlerProp,
    PointerLeaveEvent,
    into_pointer_leave_handler
);
impl_into_event_handler_prop!(ClickHandlerProp, ClickEvent, into_click_handler);
impl_into_event_handler_prop!(
    ContextMenuHandlerProp,
    ContextMenuEvent,
    into_context_menu_handler
);
impl_into_event_handler_prop!(WheelHandlerProp, WheelEvent, into_wheel_handler);
impl_into_event_handler_prop!(KeyDownHandlerProp, KeyDownEvent, into_key_down_handler);
impl_into_event_handler_prop!(KeyUpHandlerProp, KeyUpEvent, into_key_up_handler);
impl_into_event_handler_prop!(FocusHandlerProp, FocusEvent, into_focus_handler);
impl_into_event_handler_prop!(BlurHandlerProp, BlurEvent, into_blur_handler);
impl_into_event_handler_prop!(
    ImeCommitHandlerProp,
    ImeCommitEvent,
    into_ime_commit_handler
);
impl_into_event_handler_prop!(
    ImeEnabledHandlerProp,
    ImeEnabledEvent,
    into_ime_enabled_handler
);
impl_into_event_handler_prop!(
    ImeDisabledHandlerProp,
    ImeDisabledEvent,
    into_ime_disabled_handler
);
impl_into_event_handler_prop!(DragStartHandlerProp, DragStartEvent, into_drag_start_handler);
impl_into_event_handler_prop!(DragOverHandlerProp, DragOverEvent, into_drag_over_handler);
impl_into_event_handler_prop!(DragLeaveHandlerProp, DragLeaveEvent, into_drag_leave_handler);
impl_into_event_handler_prop!(DropHandlerProp, DropEvent, into_drop_handler);
impl_into_event_handler_prop!(DragEndHandlerProp, DragEndEvent, into_drag_end_handler);
impl_into_event_handler_prop!(CopyHandlerProp, CopyEvent, into_copy_handler);
impl_into_event_handler_prop!(CutHandlerProp, CutEvent, into_cut_handler);
impl_into_event_handler_prop!(PasteHandlerProp, PasteEvent, into_paste_handler);
impl_into_event_handler_prop!(
    TextAreaFocusHandlerProp,
    TextAreaFocusEvent,
    into_text_area_focus_handler
);
impl_into_event_handler_prop!(
    TextChangeHandlerProp,
    TextChangeEvent,
    into_text_change_handler
);
impl_into_event_handler_prop!(
    TextAreaRenderHandlerProp,
    TextAreaRenderString,
    into_text_area_render_handler
);

pub fn on_pointer_down<F>(handler: F) -> PointerDownHandlerProp
where
    F: FnMut(&mut PointerDownEvent) + 'static,
{
    PointerDownHandlerProp::new(handler)
}

pub fn on_pointer_up<F>(handler: F) -> PointerUpHandlerProp
where
    F: FnMut(&mut PointerUpEvent) + 'static,
{
    PointerUpHandlerProp::new(handler)
}

pub fn on_pointer_move<F>(handler: F) -> PointerMoveHandlerProp
where
    F: FnMut(&mut PointerMoveEvent) + 'static,
{
    PointerMoveHandlerProp::new(handler)
}

pub fn on_pointer_enter<F>(handler: F) -> PointerEnterHandlerProp
where
    F: FnMut(&mut PointerEnterEvent) + 'static,
{
    PointerEnterHandlerProp::new(handler)
}

pub fn on_pointer_leave<F>(handler: F) -> PointerLeaveHandlerProp
where
    F: FnMut(&mut PointerLeaveEvent) + 'static,
{
    PointerLeaveHandlerProp::new(handler)
}

pub fn on_click<F>(handler: F) -> ClickHandlerProp
where
    F: FnMut(&mut ClickEvent) + 'static,
{
    ClickHandlerProp::new(handler)
}

pub fn on_context_menu<F>(handler: F) -> ContextMenuHandlerProp
where
    F: FnMut(&mut ContextMenuEvent) + 'static,
{
    ContextMenuHandlerProp::new(handler)
}

pub fn on_wheel<F>(handler: F) -> WheelHandlerProp
where
    F: FnMut(&mut WheelEvent) + 'static,
{
    WheelHandlerProp::new(handler)
}

pub fn on_key_down<F>(handler: F) -> KeyDownHandlerProp
where
    F: FnMut(&mut KeyDownEvent) + 'static,
{
    KeyDownHandlerProp::new(handler)
}

pub fn on_key_up<F>(handler: F) -> KeyUpHandlerProp
where
    F: FnMut(&mut KeyUpEvent) + 'static,
{
    KeyUpHandlerProp::new(handler)
}

pub fn on_focus<F>(handler: F) -> FocusHandlerProp
where
    F: FnMut(&mut FocusEvent) + 'static,
{
    FocusHandlerProp::new(handler)
}

pub fn on_text_area_focus<F>(handler: F) -> TextAreaFocusHandlerProp
where
    F: FnMut(&mut TextAreaFocusEvent) + 'static,
{
    TextAreaFocusHandlerProp::new(handler)
}

pub fn on_blur<F>(handler: F) -> BlurHandlerProp
where
    F: FnMut(&mut BlurEvent) + 'static,
{
    BlurHandlerProp::new(handler)
}

pub fn on_ime_commit<F>(handler: F) -> ImeCommitHandlerProp
where
    F: FnMut(&mut ImeCommitEvent) + 'static,
{
    ImeCommitHandlerProp::new(handler)
}

pub fn on_ime_enabled<F>(handler: F) -> ImeEnabledHandlerProp
where
    F: FnMut(&mut ImeEnabledEvent) + 'static,
{
    ImeEnabledHandlerProp::new(handler)
}

pub fn on_ime_disabled<F>(handler: F) -> ImeDisabledHandlerProp
where
    F: FnMut(&mut ImeDisabledEvent) + 'static,
{
    ImeDisabledHandlerProp::new(handler)
}

pub fn on_drag_start<F>(handler: F) -> DragStartHandlerProp
where
    F: FnMut(&mut DragStartEvent) + 'static,
{
    DragStartHandlerProp::new(handler)
}

pub fn on_drag_over<F>(handler: F) -> DragOverHandlerProp
where
    F: FnMut(&mut DragOverEvent) + 'static,
{
    DragOverHandlerProp::new(handler)
}

pub fn on_drag_leave<F>(handler: F) -> DragLeaveHandlerProp
where
    F: FnMut(&mut DragLeaveEvent) + 'static,
{
    DragLeaveHandlerProp::new(handler)
}

pub fn on_drop<F>(handler: F) -> DropHandlerProp
where
    F: FnMut(&mut DropEvent) + 'static,
{
    DropHandlerProp::new(handler)
}

pub fn on_drag_end<F>(handler: F) -> DragEndHandlerProp
where
    F: FnMut(&mut DragEndEvent) + 'static,
{
    DragEndHandlerProp::new(handler)
}

pub fn on_copy<F>(handler: F) -> CopyHandlerProp
where
    F: FnMut(&mut CopyEvent) + 'static,
{
    CopyHandlerProp::new(handler)
}

pub fn on_cut<F>(handler: F) -> CutHandlerProp
where
    F: FnMut(&mut CutEvent) + 'static,
{
    CutHandlerProp::new(handler)
}

pub fn on_paste<F>(handler: F) -> PasteHandlerProp
where
    F: FnMut(&mut PasteEvent) + 'static,
{
    PasteHandlerProp::new(handler)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::platform::input::Key;

    fn new_meta() -> EventMeta {
        EventMeta::new(NodeId::default())
    }

    #[test]
    fn event_meta_default_flags() {
        let meta = new_meta();
        assert_eq!(meta.phase(), EventPhase::None);
        assert_eq!(meta.source(), EventSource::Platform);
        assert!(meta.is_trusted());
        assert!(meta.bubbles());
        assert!(meta.cancelable());
        assert!(!meta.propagation_stopped());
        assert!(!meta.immediate_propagation_stopped());
        assert!(!meta.default_prevented());
        assert!(!meta.handled());
        assert!(meta.event_id() >= 1);
    }

    #[test]
    fn prevent_default_gated_by_cancelable() {
        let mut meta = new_meta();
        meta.prevent_default();
        assert!(meta.default_prevented());

        let mut meta2 = new_meta();
        meta2.set_cancelable(false);
        meta2.prevent_default();
        assert!(!meta2.default_prevented(), "non-cancelable must ignore prevent_default");
    }

    #[test]
    fn stop_immediate_propagation_implies_stop_propagation() {
        let mut meta = new_meta();
        meta.stop_immediate_propagation();
        assert!(meta.propagation_stopped());
        assert!(meta.immediate_propagation_stopped());
    }

    #[test]
    fn event_ids_are_unique_and_monotonic() {
        let a = new_meta().event_id();
        let b = new_meta().event_id();
        let c = new_meta().event_id();
        assert!(b > a && c > b, "event ids must strictly increase");
    }

    #[test]
    fn is_trusted_reflects_source() {
        let mut meta = new_meta();
        assert!(meta.is_trusted());
        meta.set_source(EventSource::Synthetic);
        assert!(!meta.is_trusted());
        meta.set_source(EventSource::Scripted);
        assert!(!meta.is_trusted());
        meta.set_source(EventSource::Platform);
        assert!(meta.is_trusted());
    }

    #[test]
    fn key_location_from_key_maps_split_and_numpad() {
        assert_eq!(KeyLocation::from_key(Key::ShiftLeft), KeyLocation::Left);
        assert_eq!(KeyLocation::from_key(Key::ShiftRight), KeyLocation::Right);
        assert_eq!(KeyLocation::from_key(Key::ControlLeft), KeyLocation::Left);
        assert_eq!(KeyLocation::from_key(Key::NumberPad7), KeyLocation::Numpad);
        assert_eq!(KeyLocation::from_key(Key::NumberPadEnter), KeyLocation::Numpad);
        assert_eq!(KeyLocation::from_key(Key::KeyA), KeyLocation::Standard);
        assert_eq!(KeyLocation::from_key(Key::Enter), KeyLocation::Standard);
    }

    #[test]
    fn data_transfer_round_trips_text_and_files() {
        use std::path::PathBuf;
        let mut dt = DataTransfer::new();
        dt.set_text("hello");
        dt.add(DragPayload::Files(vec![PathBuf::from("/tmp/a.txt")]));
        assert_eq!(dt.text().as_deref(), Some("hello"));
        assert_eq!(dt.files().unwrap(), vec![PathBuf::from("/tmp/a.txt")]);
        assert_eq!(dt.items().len(), 2);
    }

    #[test]
    fn data_transfer_effect_allowed_defaults_to_none() {
        let mut dt = DataTransfer::new();
        assert_eq!(dt.effect_allowed(), DragEffect::None);
        dt.set_effect_allowed(DragEffect::Copy);
        assert_eq!(dt.effect_allowed(), DragEffect::Copy);
    }

    #[test]
    fn drag_over_accept_sets_effect_and_prevents_default() {
        let meta = new_meta();
        let pointer = PointerEventData {
            viewport_x: 0.0,
            viewport_y: 0.0,
            local_x: 0.0,
            local_y: 0.0,
            button: None,
            buttons: PointerButtons::default(),
            modifiers: Modifiers::default(),
            pointer_id: 0,
            pointer_type: PointerType::Mouse,
            pressure: 0.0,
            timestamp: crate::time::Instant::now(),
        };
        let mut ev = DragOverEvent {
            meta,
            pointer,
            data: DataTransfer::new(),
            drop_effect: None,
        };
        ev.accept(DragEffect::Copy);
        assert_eq!(ev.drop_effect, Some(DragEffect::Copy));
        assert!(ev.meta.default_prevented());
    }

    #[test]
    fn composed_path_empty_by_default() {
        let meta = new_meta();
        assert!(meta.composed_path().is_empty());
    }

    #[test]
    fn related_target_round_trip() {
        let mut meta = new_meta();
        assert!(meta.related_target().is_none());
        let other = EventTarget::bare(NodeId::default());
        meta.set_related_target(Some(other));
        assert!(meta.related_target().is_some());
    }

    #[test]
    fn viewport_commands_push_into_action_queue() {
        let mut meta = new_meta();
        let mut vp = meta.viewport();
        vp.request_redraw();
        vp.write_clipboard("abc");
        vp.window_command(crate::platform::WindowCommand::Minimize);
        vp.request_paste();
        let actions = meta.take_viewport_listener_actions();
        assert_eq!(actions.len(), 4);
        assert!(matches!(actions[0], EventCommand::RequestRedraw));
        assert!(matches!(actions[1], EventCommand::WriteClipboard(_)));
        assert!(matches!(
            actions[2],
            EventCommand::Window(crate::platform::WindowCommand::Minimize)
        ));
        assert!(matches!(actions[3], EventCommand::RequestPaste));
    }
}

pub fn on_change<F>(handler: F) -> TextChangeHandlerProp
where
    F: FnMut(&mut TextChangeEvent) + 'static,
{
    TextChangeHandlerProp::new(handler)
}

pub fn on_text_area_render<F>(handler: F) -> TextAreaRenderHandlerProp
where
    F: FnMut(&mut TextAreaRenderString) + 'static,
{
    TextAreaRenderHandlerProp::new(handler)
}
