use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const CODEPOINTS_PATH: &str = "assets/MaterialSymbolsOutlined.codepoints";
const FONT_PATH: &str = "assets/MaterialSymbolsOutlined.ttf";
const FAMILY_PREFIX: &str = "Material Symbols Outlined";
const POSTSCRIPT_PREFIX: &str = "MaterialSymbolsOutlined";
const GLYPH_FONT_DIR: &str = "material_symbols";

fn main() {
    println!("cargo:rerun-if-changed={CODEPOINTS_PATH}");
    println!("cargo:rerun-if-changed={FONT_PATH}");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR");
    let manifest_dir = Path::new(&manifest_dir);
    let out_dir = env::var("OUT_DIR").expect("missing OUT_DIR");
    let out_dir = Path::new(&out_dir);

    let codepoints = fs::read_to_string(manifest_dir.join(CODEPOINTS_PATH))
        .expect("failed to read Material Symbols codepoints");
    let symbols = parse_codepoints(&codepoints);

    // Every symbol becomes its own single-glyph variable font. Each generated
    // icon component references only its own font, so the linker drops the
    // font data of every icon an application never renders.
    let font_bytes =
        fs::read(manifest_dir.join(FONT_PATH)).expect("failed to read Material Symbols font");
    let font = SourceFont::parse(&font_bytes).expect("failed to parse Material Symbols font");
    let glyph_font_dir = out_dir.join(GLYPH_FONT_DIR);
    fs::create_dir_all(&glyph_font_dir).expect("failed to create Material Symbols font directory");
    let codepoint_set: BTreeSet<u32> = symbols.iter().map(|symbol| symbol.codepoint).collect();
    for &codepoint in &codepoint_set {
        let glyph_font = font.glyph_font(codepoint).unwrap_or_else(|err| {
            panic!("failed to subset Material Symbol U+{codepoint:04X}: {err}")
        });
        fs::write(glyph_font_dir.join(glyph_font_file(codepoint)), glyph_font)
            .expect("failed to write Material Symbol font");
    }

    let generated = generate_module(&symbols, &codepoint_set);
    fs::write(out_dir.join("material_symbols_outlined.rs"), generated)
        .expect("failed to write generated Material Symbols module");
}

struct Symbol<'a> {
    ligature: &'a str,
    codepoint: u32,
}

fn parse_codepoints(codepoints: &str) -> Vec<Symbol<'_>> {
    codepoints
        .lines()
        .filter_map(|line| {
            let mut parts = line.split_whitespace();
            let ligature = parts.next()?.trim();
            if ligature.is_empty() {
                return None;
            }
            let codepoint = parts
                .next()
                .and_then(|value| u32::from_str_radix(value, 16).ok())
                .unwrap_or_else(|| panic!("missing or invalid codepoint for `{ligature}`"));
            Some(Symbol {
                ligature,
                codepoint,
            })
        })
        .collect()
}

fn family_name(codepoint: u32) -> String {
    format!("{FAMILY_PREFIX} {codepoint:04X}")
}

fn postscript_name(codepoint: u32) -> String {
    format!("{POSTSCRIPT_PREFIX}-{codepoint:04X}")
}

fn glyph_font_file(codepoint: u32) -> String {
    format!("{codepoint:04x}.ttf")
}

fn glyph_static_name(codepoint: u32) -> String {
    format!("MATERIAL_SYMBOL_{codepoint:04X}")
}

fn generate_module(symbols: &[Symbol<'_>], codepoints: &BTreeSet<u32>) -> String {
    let mut output = String::new();
    output.push_str("// @generated by lib/rfgui-components/build.rs\n");
    output.push('\n');

    for &codepoint in codepoints {
        let _ = write!(
            output,
            "static {static_name}: MaterialSymbolGlyph = MaterialSymbolGlyph::new(\n    \
             \"{family}\",\n    \
             \"\\u{{{codepoint:x}}}\",\n    \
             include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{GLYPH_FONT_DIR}/{file}\")),\n\
             );\n\n",
            static_name = glyph_static_name(codepoint),
            family = family_name(codepoint),
            file = glyph_font_file(codepoint),
        );
    }

    let mut used = HashSet::new();
    for symbol in symbols {
        let component_name = unique_component_name(to_component_name(symbol.ligature), &mut used);
        let static_name = glyph_static_name(symbol.codepoint);
        output.push_str(&format!("pub struct {component_name};\n\n"));
        output.push_str(&format!(
            "impl rfgui::ui::RsxComponent<MaterialSymbolIconProps> for {component_name} {{\n"
        ));
        output.push_str(
            "    fn render(props: MaterialSymbolIconProps, _children: Vec<rfgui::ui::RsxNode>) -> rfgui::ui::RsxNode {\n",
        );
        output.push_str(&format!(
            "        render_material_symbol_icon(&{static_name}, props)\n"
        ));
        output.push_str("    }\n");
        output.push_str("}\n\n");
        output.push_str("#[rfgui::ui::component]\n");
        output.push_str(&format!("impl rfgui::ui::RsxTag for {component_name} {{\n"));
        output.push_str("    type Props = __MaterialSymbolIconPropsInit;\n");
        output.push_str("    type StrictProps = MaterialSymbolIconProps;\n");
        output.push_str("    const ACCEPTS_CHILDREN: bool = false;\n");
        output.push_str(
            "    fn into_strict(props: Self::Props) -> Self::StrictProps { props.into() }\n",
        );
        output.push_str("    fn create_node(\n");
        output.push_str("        props: Self::StrictProps,\n");
        output.push_str("        children: Vec<rfgui::ui::RsxNode>,\n");
        output.push_str("        _key: Option<rfgui::ui::RsxKey>,\n");
        output.push_str("    ) -> rfgui::ui::RsxNode {\n");
        output.push_str(&format!(
            "        <Self as rfgui::ui::RsxComponent<MaterialSymbolIconProps>>::render(props, children)\n"
        ));
        output.push_str("    }\n");
        output.push_str("}\n\n");
    }

    output
}

fn unique_component_name(base: String, used: &mut HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }

    let mut index = 2_u32;
    loop {
        let candidate = format!("{base}{index}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn to_component_name(ligature: &str) -> String {
    let mut ident = String::new();
    for segment in ligature.split('_').filter(|segment| !segment.is_empty()) {
        push_segment(&mut ident, segment);
    }

    if ident.is_empty() {
        ident.push_str("MaterialSymbol");
    }

    if ident
        .as_bytes()
        .first()
        .is_some_and(|byte| byte.is_ascii_digit())
    {
        ident.insert_str(0, "Icon");
    }

    ident.push_str("Icon");
    ident
}

fn push_segment(output: &mut String, segment: &str) {
    let mut chunk = String::new();

    for character in segment.chars() {
        if character.is_ascii_alphanumeric() {
            chunk.push(character);
            continue;
        }

        flush_chunk(output, &mut chunk);
    }

    flush_chunk(output, &mut chunk);
}

fn flush_chunk(output: &mut String, chunk: &mut String) {
    if chunk.is_empty() {
        return;
    }

    let mut chars = chunk.chars();
    if let Some(first) = chars.next() {
        output.push(first.to_ascii_uppercase());
        output.push_str(chars.as_str());
    }
    chunk.clear();
}

// ---------------------------------------------------------------------------
// Single-glyph variable font subsetting
// ---------------------------------------------------------------------------

/// Tables copied verbatim. They do not depend on glyph ids.
const VERBATIM_TABLES: [&[u8; 4]; 4] = [b"OS/2", b"STAT", b"avar", b"fvar"];

/// The bundled variable font, parsed just far enough to cut one glyph out
/// together with its outline variations.
struct SourceFont<'a> {
    tables: BTreeMap<[u8; 4], &'a [u8]>,
    glyph_offsets: Vec<usize>,
    horizontal_metric_count: usize,
    cmap_groups: Vec<(u32, u32, u32)>,
}

impl<'a> SourceFont<'a> {
    fn parse(data: &'a [u8]) -> Result<Self, String> {
        let table_count = usize::from(read_u16(data, 4)?);
        let mut tables = BTreeMap::new();
        for index in 0..table_count {
            let record = 12 + index * 16;
            let tag: [u8; 4] = slice(data, record, 4)?
                .try_into()
                .map_err(|_| "invalid table tag".to_string())?;
            let offset = read_u32(data, record + 8)? as usize;
            let length = read_u32(data, record + 12)? as usize;
            tables.insert(tag, slice(data, offset, length)?);
        }

        let mut font = Self {
            tables,
            glyph_offsets: Vec::new(),
            horizontal_metric_count: 0,
            cmap_groups: Vec::new(),
        };
        let glyph_count = usize::from(read_u16(font.table(b"maxp")?, 4)?);
        let long_offsets = read_u16(font.table(b"head")?, 50)? == 1;
        let loca = font.table(b"loca")?;
        font.glyph_offsets = (0..=glyph_count)
            .map(|glyph| {
                if long_offsets {
                    read_u32(loca, glyph * 4).map(|offset| offset as usize)
                } else {
                    read_u16(loca, glyph * 2).map(|offset| usize::from(offset) * 2)
                }
            })
            .collect::<Result<_, _>>()?;
        font.horizontal_metric_count = usize::from(read_u16(font.table(b"hhea")?, 34)?);
        if font.horizontal_metric_count == 0 {
            return Err("hhea declares no horizontal metrics".into());
        }
        font.cmap_groups = parse_cmap_groups(font.table(b"cmap")?)?;
        Ok(font)
    }

    fn table(&self, tag: &[u8; 4]) -> Result<&'a [u8], String> {
        self.tables
            .get(tag)
            .copied()
            .ok_or_else(|| format!("missing `{}` table", String::from_utf8_lossy(tag)))
    }

    fn glyph_id(&self, codepoint: u32) -> Option<usize> {
        let index = self
            .cmap_groups
            .partition_point(|&(_, end, _)| end < codepoint);
        let &(start, end, start_glyph) = self.cmap_groups.get(index)?;
        (start <= codepoint && codepoint <= end)
            .then(|| (start_glyph + (codepoint - start)) as usize)
    }

    fn outline(&self, glyph: usize) -> Result<&'a [u8], String> {
        let start = *self
            .glyph_offsets
            .get(glyph)
            .ok_or("glyph id out of range")?;
        let end = *self
            .glyph_offsets
            .get(glyph + 1)
            .ok_or("glyph id out of range")?;
        slice(self.table(b"glyf")?, start, end.saturating_sub(start))
    }

    fn horizontal_metric(&self, glyph: usize) -> Result<(u16, i16), String> {
        let hmtx = self.table(b"hmtx")?;
        let count = self.horizontal_metric_count;
        let advance = read_u16(hmtx, glyph.min(count - 1) * 4)?;
        let side_bearing = if glyph < count {
            read_i16(hmtx, glyph * 4 + 2)?
        } else {
            read_i16(hmtx, count * 4 + (glyph - count) * 2)?
        };
        Ok((advance, side_bearing))
    }

    /// Builds a font holding an empty `.notdef` (glyph 0) and the symbol
    /// (glyph 1), keeping every variation axis. The outline is copied
    /// verbatim, so its `gvar` deltas stay valid without point renumbering.
    /// `HVAR` is omitted: without it, advance variations come from the
    /// `gvar` phantom points.
    fn glyph_font(&self, codepoint: u32) -> Result<Vec<u8>, String> {
        let glyph = self
            .glyph_id(codepoint)
            .filter(|&glyph| glyph != 0)
            .ok_or("codepoint is not mapped")?;
        let outline = self.outline(glyph)?;
        if outline.len() >= 2 && read_i16(outline, 0)? < 0 {
            return Err("composite glyphs are not supported".into());
        }
        let (notdef_advance, _) = self.horizontal_metric(0)?;
        let (advance, side_bearing) = self.horizontal_metric(glyph)?;

        let mut glyf = outline.to_vec();
        pad_to_four(&mut glyf);
        let mut loca = Vec::new();
        for offset in [0, 0, glyf.len() as u32] {
            loca.extend_from_slice(&offset.to_be_bytes());
        }
        let mut hmtx = Vec::new();
        hmtx.extend_from_slice(&notdef_advance.to_be_bytes());
        hmtx.extend_from_slice(&0_i16.to_be_bytes());
        hmtx.extend_from_slice(&advance.to_be_bytes());
        hmtx.extend_from_slice(&side_bearing.to_be_bytes());

        let mut head = self.table(b"head")?.to_vec();
        patch(&mut head, 8, &0_u32.to_be_bytes())?;
        patch(&mut head, 50, &1_i16.to_be_bytes())?;
        let mut hhea = self.table(b"hhea")?.to_vec();
        patch(&mut hhea, 34, &2_u16.to_be_bytes())?;
        let mut maxp = self.table(b"maxp")?.to_vec();
        patch(&mut maxp, 4, &2_u16.to_be_bytes())?;
        let mut post = slice(self.table(b"post")?, 0, 32)?.to_vec();
        patch(&mut post, 0, &0x0003_0000_u32.to_be_bytes())?;

        let mut tables = vec![
            (*b"cmap", single_mapping_cmap(codepoint)),
            (*b"glyf", glyf),
            (*b"gvar", self.glyph_variations(glyph)?),
            (*b"head", head),
            (*b"hhea", hhea),
            (*b"hmtx", hmtx),
            (*b"loca", loca),
            (*b"maxp", maxp),
            (*b"name", self.renamed_name_table(codepoint)?),
            (*b"post", post),
        ];
        for tag in VERBATIM_TABLES {
            tables.push((*tag, self.table(tag)?.to_vec()));
        }
        Ok(assemble_font(tables))
    }

    /// `gvar` for glyphs 0 (no variations) and 1 (the symbol's variation
    /// data, copied verbatim). Shared tuples are glyph independent.
    fn glyph_variations(&self, glyph: usize) -> Result<Vec<u8>, String> {
        let gvar = self.table(b"gvar")?;
        let axis_count = read_u16(gvar, 4)?;
        let shared_tuple_count = read_u16(gvar, 6)?;
        let shared_tuples_offset = read_u32(gvar, 8)? as usize;
        let long_offsets = read_u16(gvar, 14)? & 1 == 1;
        let data_offset = read_u32(gvar, 16)? as usize;
        let variation_offset = |glyph: usize| -> Result<usize, String> {
            if long_offsets {
                read_u32(gvar, 20 + glyph * 4).map(|offset| offset as usize)
            } else {
                read_u16(gvar, 20 + glyph * 2).map(|offset| usize::from(offset) * 2)
            }
        };
        let start = variation_offset(glyph)?;
        let end = variation_offset(glyph + 1)?;
        let variations = slice(gvar, data_offset + start, end.saturating_sub(start))?;
        let shared_tuples = slice(
            gvar,
            shared_tuples_offset,
            usize::from(axis_count) * usize::from(shared_tuple_count) * 2,
        )?;

        const HEADER_LEN: usize = 20;
        const OFFSETS_LEN: usize = 3 * 4;
        let shared_offset = HEADER_LEN + OFFSETS_LEN;
        let mut array_offset = shared_offset + shared_tuples.len();
        array_offset += array_offset % 2;

        let mut table = Vec::with_capacity(array_offset + variations.len());
        table.extend_from_slice(&1_u16.to_be_bytes());
        table.extend_from_slice(&0_u16.to_be_bytes());
        table.extend_from_slice(&axis_count.to_be_bytes());
        table.extend_from_slice(&shared_tuple_count.to_be_bytes());
        table.extend_from_slice(&(shared_offset as u32).to_be_bytes());
        table.extend_from_slice(&2_u16.to_be_bytes());
        table.extend_from_slice(&1_u16.to_be_bytes());
        table.extend_from_slice(&(array_offset as u32).to_be_bytes());
        for offset in [0, 0, variations.len() as u32] {
            table.extend_from_slice(&offset.to_be_bytes());
        }
        table.extend_from_slice(shared_tuples);
        table.resize(array_offset, 0);
        table.extend_from_slice(variations);
        Ok(table)
    }

    /// Keeps every name record (`fvar` and `STAT` reference instance and
    /// axis names by id) but gives the font its own family, so each symbol
    /// registers as a distinct face.
    fn renamed_name_table(&self, codepoint: u32) -> Result<Vec<u8>, String> {
        let name = self.table(b"name")?;
        let count = usize::from(read_u16(name, 2)?);
        let storage = usize::from(read_u16(name, 4)?);
        let family = family_name(codepoint);
        let full_name = format!("{family} Regular");
        let postscript = postscript_name(codepoint);

        let mut records = Vec::with_capacity(count);
        for index in 0..count {
            let record = 6 + index * 12;
            let platform = read_u16(name, record)?;
            let encoding = read_u16(name, record + 2)?;
            let language = read_u16(name, record + 4)?;
            let name_id = read_u16(name, record + 6)?;
            let length = usize::from(read_u16(name, record + 8)?);
            let offset = usize::from(read_u16(name, record + 10)?);
            let replacement = match name_id {
                1 | 16 => Some(family.as_str()),
                3 | 6 => Some(postscript.as_str()),
                4 => Some(full_name.as_str()),
                _ => None,
            };
            let string = match replacement {
                Some(value) => encode_name(platform, value),
                None => slice(name, storage + offset, length)?.to_vec(),
            };
            records.push((platform, encoding, language, name_id, string));
        }

        let storage_offset = 6 + records.len() * 12;
        let mut table = Vec::new();
        table.extend_from_slice(&0_u16.to_be_bytes());
        table.extend_from_slice(&(records.len() as u16).to_be_bytes());
        table.extend_from_slice(&(storage_offset as u16).to_be_bytes());
        let mut strings = Vec::new();
        for (platform, encoding, language, name_id, string) in &records {
            for value in [*platform, *encoding, *language, *name_id] {
                table.extend_from_slice(&value.to_be_bytes());
            }
            table.extend_from_slice(&(string.len() as u16).to_be_bytes());
            table.extend_from_slice(&(strings.len() as u16).to_be_bytes());
            strings.extend_from_slice(string);
        }
        table.extend_from_slice(&strings);
        Ok(table)
    }
}

/// UTF-16BE for Unicode/Windows records, single-byte (ASCII) otherwise.
fn encode_name(platform: u16, value: &str) -> Vec<u8> {
    if platform == 1 {
        value.bytes().collect()
    } else {
        value.encode_utf16().flat_map(u16::to_be_bytes).collect()
    }
}

fn parse_cmap_groups(cmap: &[u8]) -> Result<Vec<(u32, u32, u32)>, String> {
    let subtable_count = usize::from(read_u16(cmap, 2)?);
    for index in 0..subtable_count {
        let record = 4 + index * 8;
        let platform = read_u16(cmap, record)?;
        let encoding = read_u16(cmap, record + 2)?;
        let offset = read_u32(cmap, record + 4)? as usize;
        let full_unicode = (platform == 3 && encoding == 10) || (platform == 0 && encoding >= 4);
        if !full_unicode || read_u16(cmap, offset)? != 12 {
            continue;
        }
        let group_count = read_u32(cmap, offset + 12)? as usize;
        return (0..group_count)
            .map(|group| {
                let base = offset + 16 + group * 12;
                Ok((
                    read_u32(cmap, base)?,
                    read_u32(cmap, base + 4)?,
                    read_u32(cmap, base + 8)?,
                ))
            })
            .collect();
    }
    Err("no format 12 Unicode cmap subtable".into())
}

/// Windows full-Unicode format 12 cmap mapping `codepoint` to glyph 1.
fn single_mapping_cmap(codepoint: u32) -> Vec<u8> {
    let mut table = Vec::new();
    table.extend_from_slice(&0_u16.to_be_bytes());
    table.extend_from_slice(&1_u16.to_be_bytes());
    table.extend_from_slice(&3_u16.to_be_bytes());
    table.extend_from_slice(&10_u16.to_be_bytes());
    table.extend_from_slice(&12_u32.to_be_bytes());
    table.extend_from_slice(&12_u16.to_be_bytes());
    table.extend_from_slice(&0_u16.to_be_bytes());
    table.extend_from_slice(&28_u32.to_be_bytes());
    table.extend_from_slice(&0_u32.to_be_bytes());
    table.extend_from_slice(&1_u32.to_be_bytes());
    table.extend_from_slice(&codepoint.to_be_bytes());
    table.extend_from_slice(&codepoint.to_be_bytes());
    table.extend_from_slice(&1_u32.to_be_bytes());
    table
}

fn assemble_font(mut tables: Vec<([u8; 4], Vec<u8>)>) -> Vec<u8> {
    tables.sort_by(|left, right| left.0.cmp(&right.0));
    let table_count = tables.len() as u16;
    let entry_selector = (u16::BITS - 1 - table_count.leading_zeros()) as u16;
    let search_range = (1_u16 << entry_selector) * 16;
    let range_shift = table_count * 16 - search_range;

    let mut font = Vec::new();
    font.extend_from_slice(&0x0001_0000_u32.to_be_bytes());
    for value in [table_count, search_range, entry_selector, range_shift] {
        font.extend_from_slice(&value.to_be_bytes());
    }
    let mut offset = 12 + tables.len() * 16;
    let mut head_offset = None;
    for (tag, data) in &tables {
        if tag == b"head" {
            head_offset = Some(offset);
        }
        font.extend_from_slice(tag);
        font.extend_from_slice(&checksum(data).to_be_bytes());
        font.extend_from_slice(&(offset as u32).to_be_bytes());
        font.extend_from_slice(&(data.len() as u32).to_be_bytes());
        offset += data.len().next_multiple_of(4);
    }
    for (_, data) in &tables {
        font.extend_from_slice(data);
        pad_to_four(&mut font);
    }
    if let Some(head) = head_offset {
        let adjustment = 0xB1B0_AFBA_u32.wrapping_sub(checksum(&font));
        font[head + 8..head + 12].copy_from_slice(&adjustment.to_be_bytes());
    }
    font
}

fn checksum(data: &[u8]) -> u32 {
    data.chunks(4).fold(0_u32, |sum, chunk| {
        let mut word = [0_u8; 4];
        word[..chunk.len()].copy_from_slice(chunk);
        sum.wrapping_add(u32::from_be_bytes(word))
    })
}

fn pad_to_four(data: &mut Vec<u8>) {
    data.resize(data.len().next_multiple_of(4), 0);
}

fn patch(data: &mut [u8], offset: usize, bytes: &[u8]) -> Result<(), String> {
    data.get_mut(offset..offset + bytes.len())
        .ok_or_else(|| format!("table too short to patch offset {offset}"))?
        .copy_from_slice(bytes);
    Ok(())
}

fn slice(data: &[u8], offset: usize, length: usize) -> Result<&[u8], String> {
    data.get(offset..offset + length)
        .ok_or_else(|| format!("read of {length} bytes at {offset} is out of bounds"))
}

fn read_u16(data: &[u8], offset: usize) -> Result<u16, String> {
    Ok(u16::from_be_bytes(
        slice(data, offset, 2)?.try_into().unwrap(),
    ))
}

fn read_i16(data: &[u8], offset: usize) -> Result<i16, String> {
    Ok(i16::from_be_bytes(
        slice(data, offset, 2)?.try_into().unwrap(),
    ))
}

fn read_u32(data: &[u8], offset: usize) -> Result<u32, String> {
    Ok(u32::from_be_bytes(
        slice(data, offset, 4)?.try_into().unwrap(),
    ))
}
