use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=assets/MaterialSymbolsOutlined.codepoints");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR");
    let codepoints_path =
        Path::new(&manifest_dir).join("assets/MaterialSymbolsOutlined.codepoints");
    let output_path = Path::new(&env::var("OUT_DIR").expect("missing OUT_DIR"))
        .join("material_symbols_outlined.rs");

    let codepoints =
        fs::read_to_string(&codepoints_path).expect("failed to read Material Symbols codepoints");
    let generated = generate_components(&codepoints);
    fs::write(output_path, generated).expect("failed to write generated Material Symbols module");
}

fn generate_components(codepoints: &str) -> String {
    let mut output = String::new();
    output.push_str("// @generated by lib/rfgui-components/build.rs\n");
    output.push('\n');

    let mut used = HashSet::new();
    for line in codepoints.lines() {
        let ligature = line.split_whitespace().next().unwrap_or_default().trim();
        if ligature.is_empty() {
            continue;
        }
        let component_name = unique_component_name(to_component_name(ligature), &mut used);
        output.push_str(&format!("pub struct {component_name};\n\n"));
        output.push_str(&format!(
            "impl rfgui::ui::RsxComponent<MaterialSymbolIconProps> for {component_name} {{\n"
        ));
        output.push_str(
            "    fn render(props: MaterialSymbolIconProps, _children: Vec<rfgui::ui::RsxNode>) -> rfgui::ui::RsxNode {\n",
        );
        output.push_str(&format!(
            "        render_material_symbol_icon(\"{ligature}\", props)\n"
        ));
        output.push_str("    }\n");
        output.push_str("}\n\n");
        output.push_str(&format!(
            "impl rfgui::ui::RsxChildrenPolicy for {component_name} {{\n"
        ));
        output.push_str("    const ACCEPTS_CHILDREN: bool = false;\n");
        output.push_str("}\n\n");
    }

    output
}

fn unique_component_name(base: String, used: &mut HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }

    let mut index = 2_u32;
    loop {
        let candidate = format!("{base}{index}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn to_component_name(ligature: &str) -> String {
    let mut ident = String::new();
    for segment in ligature.split('_').filter(|segment| !segment.is_empty()) {
        push_segment(&mut ident, segment);
    }

    if ident.is_empty() {
        ident.push_str("MaterialSymbol");
    }

    if ident.as_bytes().first().is_some_and(|byte| byte.is_ascii_digit()) {
        ident.insert_str(0, "Icon");
    }

    ident.push_str("Icon");
    ident
}

fn push_segment(output: &mut String, segment: &str) {
    let mut chunk = String::new();

    for character in segment.chars() {
        if character.is_ascii_alphanumeric() {
            chunk.push(character);
            continue;
        }

        flush_chunk(output, &mut chunk);
    }

    flush_chunk(output, &mut chunk);
}

fn flush_chunk(output: &mut String, chunk: &mut String) {
    if chunk.is_empty() {
        return;
    }

    let mut chars = chunk.chars();
    if let Some(first) = chars.next() {
        output.push(first.to_ascii_uppercase());
        output.push_str(chars.as_str());
    }
    chunk.clear();
}
